config/routes.rb
Rails.application.routes.draw do
  scope "blog", :module => :blogr, :as => "blogr" do
    root :to => "posts#index"
    resources :posts, :only => [:index, :show] do
      resource :comments
    end
    resources :pages, :only => [:index, :show] do
      resources :inquiries
    end
    namespace :admin do
      root :to => "sessions#new"
      get "logout" => "sessions#destroy", :as => "logout"
      get "login" => "sessions#new", :as => "login"
      get "sign_up" => "users#new", :as => "sign_up"
      resources :posts do
        get :publish, :on => :member
        resource :comments
      end
      resources :sessions do
        get :dashboard, :on => :collection
      end
      resources :pages do
        get :hide, :on => :member
        get :unhide, :on => :member
      end
      match 'pages/update_positions/', :controller=>'pages', :action => 'update_positions'
      match 'pages/update_page/', :controller=>'pages', :action => 'update_page'
      resources :categories, :users, :sessions
      resources :medias do
        get :overview, :on => :collection
      end
    end
  end
end

app/models/blogr/media.rb
module Blogr
  class Media < ActiveRecord::Base
    set_table_name "blogr_medias"

    validates_presence_of :title
    validates_attachment_presence :image
    has_attached_file :image, :styles => { :thumb => "100x100>", :medium => "300x300>", :big => "800x800>"  }

  end
end

app/controllers/blogr/admin/medias_controller.rb
module Blogr
  class Admin::MediasController < Admin::BlogrAdminController
    unloadable

    before_filter :get_media, :only => [:edit, :show, :update, :destroy, :publish]

    def index
      @medias = Media.page(params[:page])
    end

    def new
      @media = Media.new
    end

    def edit
    end

    def create
      @media = Media.new(params[:blogr_media])
      if @media.save
        Activity.create :who => current_user.name, :what => "New media created: #{@media.title}"
        redirect_to blogr_admin_medias_path, :notice => "Media was successfully created."
      else
        render :action => "new"
      end
    end

    def update
      if @media.update_attributes(params[:blogr_media])
        Activity.create :who => current_user.name, :what => "Media updated: #{@media.title}"
        redirect_to blogr_admin_medias_path, :notice => "Media was successfully updated."
      else
        render :action => "edit"
      end
    end

    def destroy
      @media.destroy
      Activity.create :who => current_user.name, :what => "Destroyed: #{@media.title}"
      redirect_to blogr_admin_medias_path, :notice => "Media was successfully deleted."
    end

    def overview
      @medias = Media.page(params[:page])
      render :layout => "images"
    end

    private

    def get_media
      @media = Media.find(params[:id])
    end
  end
end

app/views/blogr/admin/medias/_form.html.erb
<%= form_for @media, :url => blogr_admin_medias_path, :html => { :multipart => true } do |f|%>
    <%= render "blogr/shared/error_messages", :object => @media %>
    <table>
        <tr>
            <td><%= f.label :title%></td>
            <td><%= f.text_field :title%></td>
        </tr>
        <tr>
            <td><%= f.label :image%></td>
            <td><%= f.file_field :image, :class => "editor"%></td>
        </tr>
        <tr>
            <td><%= f.submit "create media", :class => "button button-green" %></td>
        </tr>
    </table>
<% end %>

app/views/blogr/admin/medias/edit.html.erb
<div class="posts-box main-content">
    <div class="posts-header">
        <ul class="action-buttons clearfix fr">
            <li><%#= link_to "new page", new_blogr_admin_page_path, :class => "button button-gray"%></li>
            <li><%= link_to "Back", blogr_admin_medias_path, :class => "button button-gray"%></li>
        </ul>
        <h2>Edit media</h2>
    </div>
    <div class="posts-box-content">
        <div class="form">
            <%= form_for( @media, :url => blogr_admin_media_path(:id => @media.id), :html => { :method => "put", :multipart => true }) do |f|%>
                <%= render "blogr/shared/error_messages", :object => @media %>
                <table>
                    <tr>
                        <td><%= f.label :title%></td>
                        <td><%= f.text_field :title%></td>
                    </tr>
                    <tr>
                        <td><%= f.label :image%></td>
                        <td><%= f.file_field :image, :class => "editor"%></td>
                    </tr>
                    <tr>
                        <td><%= f.submit "create media", :class => "button button-green" %></td>
                    </tr>
                </table>
            <% end %>
        </div>
    </div>
</div>

app/views/blogr/admin/medias/index.html.erb
<div class="medias-box main-content">
    <div class="medias-header">
        <ul class="action-buttons clearfix fr">
            <li><%= link_to "New media", new_blogr_admin_media_path, :class => "button button-gray"%></li>
            <li><a href="#" class="button button-gray">Archive</a></li>
        </ul>
        <h2>Medias Index</h2>
    </div>
    <div class="medias-box-content">
        <div class="table">
            <table>
                <thead>
                    <tr>
                        <th><input class="check-all" type="checkbox"></th>
                        <th>Title</th>
                        <th>Image</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <td colspan="6">
                            <div class="bulk-actions align-left">
                                <select name="dropdown">
                                    <option value="option1">Choose an action...</option>
                                    <option value="option2">Edit</option>
                                    <option value="option3">Delete</option>
                                </select>
                                <a class="button" href="#">Apply to selected</a>
                            </div>
                            <%= paginate @medias%>
                            <div class="clear"></div>
                        </td>
                    </tr>
                </tfoot>
                <tbody>
                    <% @medias.each do |media|%>
                        <tr class=<%= cycle("even", "odd")%>>
                            <td><input type="checkbox"></td>
                            <td><%= media.title %></td>
                            <td><%= image_tag media.image.url(:thumb)%></td>
                            <td>
                                <%= link_to image_tag("edit.png"), edit_blogr_admin_media_path(media)%>
                                <%= link_to image_tag("delete.png"), blogr_admin_media_path(media), :method => :delete%>
                            </td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/blogr/admin/medias/new.html.erb
<div class="posts-box main-content">
    <div class="posts-header">
        <ul class="action-buttons clearfix fr">
            <li><%#= link_to "new page", new_blogr_admin_page_path, :class => "button button-gray"%></li>
            <li><%= link_to "Back", blogr_admin_medias_path, :class => "button button-gray"%></li>
        </ul>
        <h2>New media</h2>
    </div>
    <div class="posts-box-content">
        <div class="form">
            <%= render "form"%>
        </div>
    </div>
</div>

app/views/blogr/admin/medias/overview.html.erb
<div class="main-content">
    <div class="pages-header">
        <h2>Media</h2>
    </div>
    <div class="pages-box-content">
        <div class="table">
            <div id="pages-holder">
                <table>
                    <% @medias.each do |media|%>
                    <!-- #{media.image.url(:thumb)} -->
                    <tr>
                        <td><%= link_to_function (image_tag media.image.url(:thumb)), "insertTinymceImage()" %></td>
                    </tr>
                    <% end %>
                </table>
                <%= paginate @medias%>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
function insertTinymceImage() {
        // opener.tinyMCE.execCommand('mceInsertContent', false, '<img src="cake" />');
        window.close();
}
</script>