config/routes.rb
Rails.application.routes.draw do
  scope "blog", :module => :blogr, :as => "blogr" do
    root :to => "posts#index"
    resources :posts, :only => [:index, :show] do
      resource :comments
    end
    resources :pages, :only => [:index, :show] do
      resources :inquiries
    end
    namespace :admin do
      root :to => "sessions#new"
      get "logout" => "sessions#destroy", :as => "logout"
      get "login" => "sessions#new", :as => "login"
      get "sign_up" => "users#new", :as => "sign_up"
      resources :posts do
        get :publish, :on => :member
        resource :comments
      end
      resources :sessions do
        get :dashboard, :on => :collection
      end
      resources :pages do
        get :hide, :on => :member
        get :unhide, :on => :member
      end
      match 'pages/update_positions/', :controller=>'pages', :action => 'update_positions'
      match 'pages/update_page/', :controller=>'pages', :action => 'update_page'
      resources :categories, :users, :sessions
      resources :medias do
        get :overview, :on => :collection
      end
    end
  end
end

app/views/blogr/admin/pages/_form.html.erb
<%= form_for @page, :url => blogr_admin_pages_path do |f|%>
    <%= render "blogr/shared/error_messages", :object => @page %>
    <table>
        <tr>
            <td><%= f.label :menu_item%></td>
            <td><%= f.text_field :menu_item%></td>
        </tr>
        <tr>
            <td><%= f.label :title%></td>
            <td><%= f.text_field :title%></td>
        </tr>
        <tr>
            <td><%= f.label :body%></td>
            <td><%= f.text_area :body, :class => "editor"%></td>
        </tr>
        <tr>
            <td><%= f.label :has_inquire %></td>
            <td><%= f.check_box :has_inquire%></td>
        </tr>
        <tr>
            <td><%= f.submit "create page", :class => "button button-green" %></td>
        </tr>
    </table>
<% end %>

app/views/blogr/admin/pages/_page.html.erb
<table id="pagesTable">
    <thead>
        <tr>
            <th><input class="check-all" type="checkbox"></th>
            <th>Title</th>
            <th>Menu title</th>
            <th>Hide</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <td colspan="6">
                <div class="bulk-actions align-left">
                    <select name="dropdown">
                        <option value="option1">Choose an action...</option>
                        <option value="option2">Edit</option>
                        <option value="option3">Delete</option>
                    </select>
                    <a class="button" href="#">Apply to selected</a>
                </div>
                <%#= paginate @pages%>
                <div class="clear"></div>
            </td>
        </tr>
    </tfoot>
    <tbody>
        <% @pages.each do |page|%>
            <tr class=<%= cycle("even", "odd")%>  id="<%= page.position %>">
                <td><input type="checkbox"></td>
                <td><%= link_to page.title, blogr_admin_page_path(page) %></td>
                <td><%= page.menu_item%></td>
                <td><%= page.hidden == true ? (link_to "Unhide", unhide_blogr_admin_page_path(page)): (link_to "Hide", hide_blogr_admin_page_path(page)) %></td>
                <td>
                    <%= link_to image_tag("edit.png"), edit_blogr_admin_page_path(page) unless page.title.downcase == "blog"%>
                    <%= link_to image_tag("delete.png"), blogr_admin_page_path(page), :method => :delete unless page.title.downcase == "blog"%>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

<script type="text/javascript">
    var positionArr = Array();
    $("#pagesTable").tableDnD({
		onDragClass: "drag",
        onDrop: function(table, row) {
            var rows = table.tBodies[0].rows;
            for (var i=0; i<rows.length; i++) {
                positionArr.push(rows[i].id);
            }
            $.ajax({
               type: "POST",
               url: "pages/update_positions/",
               data: "changed="+row.id+"&positionArray="+positionArr,
               success: function(msg){
               }
            });
            positionArr = Array();

            $.ajax({
		        type: "POST",
		        url: "pages/update_page/",
			    dataType: 'script'
		    });
	    }
    });
</script>

app/views/blogr/admin/pages/edit.html.erb
<div class="posts-box main-content">
    <div class="posts-header">
        <ul class="action-buttons clearfix fr">
            <li><%#= link_to "new page", new_blogr_admin_page_path, :class => "button button-gray"%></li>
            <li><%= link_to "Back", blogr_admin_pages_path, :class => "button button-gray"%></li>
        </ul>
        <h2>Edit page</h2>
    </div>
    <div class="posts-box-content">
        <div class="form">
            <%= form_for( @page, :url => blogr_admin_page_path(:id => @page.id), :html => { :method => "put" }) do |f|%>
                <%= render "blogr/shared/error_messages", :object => @page %>
                <table>
                    <tr>
                        <td><%= f.label :menu_item%></td>
                        <td><%= f.text_field :menu_item%></td>
                    </tr>
                    <tr>
                        <td><%= f.label :title%></td>
                        <td><%= f.text_field :title%></td>
                    </tr>
                    <tr>
                        <td><%= f.label :body%></td>
                        <td><%= f.text_area :body, :class => "editor"%></td>
                    </tr>
                    <tr>
                        <td><%= f.label :has_inquire %></td>
                        <td><%= f.check_box :has_inquire%></td>
                    </tr>
                    <tr>
                        <td><%= f.submit "create page", :class => "button button-green" %></td>
                    </tr>
                </table>
            <% end %>
        </div>
    </div>
</div>

app/views/blogr/admin/pages/index.html.erb
<div class="pages-box main-content">
    <div class="pages-header">
        <ul class="action-buttons clearfix fr">
            <li><%= link_to "New page", new_blogr_admin_page_path, :class => "button button-gray"%></li>
            <li><a href="#" class="button button-gray">Archive</a></li>
        </ul>
        <h2>Pages Index</h2>
    </div>
    <div class="pages-box-content">
        <div class="table">
            <div id="pages-holder">
              <%= render :partial => "page", :locals => {:pages => @pages} %>
            </div>
        </div>
    </div>
</div>

app/views/blogr/admin/pages/new.html.erb
<div class="pages-box main-content">
    <div class="pages-header">
        <ul class="action-buttons clearfix fr">
            <li><%#= link_to "new page", new_blogr_admin_page_path, :class => "button button-gray"%></li>
            <li><%= link_to "Back", blogr_admin_pages_path, :class => "button button-gray"%></li>
        </ul>
        <h2>New page</h2>
    </div>
    <div class="pages-box-content">
        <div class="form">
            <%= render "form"%>
        </div>
    </div>
</div>

app/views/blogr/admin/pages/show.html.erb
<div class="pages-box main-content">
    <div class="pages-header">
        <ul class="action-buttons clearfix fr">
            <li><%= link_to "Edit page", edit_blogr_admin_page_path(@page), :class => "button button-gray"%></li>
            <li><%= link_to "Back", blogr_admin_pages_path, :class => "button button-gray"%></li>
        </ul>
        <h2><%= @page.title%></h2>
    </div>
    <div class="posts-box-content">
        <div class="table">
            <%= raw @page.body %>
        </div>
    </div>
</div>

<% if @page.has_inquire?%>
<div class="pages-box main-content">
    <div class="pages-header">
        <ul class="action-buttons clearfix fr">
            <li><%#= link_to "new page", new_blogr_admin_page_path, :class => "button button-gray"%></li>
            <li><%#= link_to "Back", blogr_admin_pages_path, :class => "button button-gray"%></li>
        </ul>
        <h2>Inquiries</h2>
    </div>
    <div class="posts-box-content">
        <div class="table">
            <table id="pagesTable">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Question</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <td colspan="6">
                            <%#= paginate @pages%>
                            <div class="clear"></div>
                        </td>
                    </tr>
                </tfoot>
                <tbody>
                    <% @page.inquiries.each do |inquire|%>
                        <tr class=<%= cycle("even", "odd")%>>
                            <td><%= inquire.name%></td>
                            <td><%= inquire.email %></td>
                            <td><%= inquire.question %></td>
                            <td>
                                <%#= link_to image_tag("edit.png"), edit_blogr_admin_page_path(page)%>
                                <%#= link_to image_tag("delete.png"), blogr_admin_page_path(page), :method => :delete unless page.title.downcase == "blog"%>
                                <%#= button_to "Delete", blogr_admin_page_path(page), :method => :delete unless page.title.downcase == "blog" %>
                            </td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>
<% end %>