config/routes.rb
Rails.application.routes.draw do
  scope "blog", :module => :blogr, :as => "blogr" do
    root :to => "posts#index"
    resources :posts, :only => [:index, :show] do
      resource :comments
    end
    resources :pages, :only => [:index, :show] do
      resources :inquiries
    end
    namespace :admin do
      root :to => "sessions#new"
      get "logout" => "sessions#destroy", :as => "logout"
      get "login" => "sessions#new", :as => "login"
      get "sign_up" => "users#new", :as => "sign_up"
      resources :posts do
        get :publish, :on => :member
        resource :comments
      end
      resources :sessions do
        get :dashboard, :on => :collection
      end
      resources :pages do
        get :hide, :on => :member
        get :unhide, :on => :member
      end
      match 'pages/update_positions/', :controller=>'pages', :action => 'update_positions'
      match 'pages/update_page/', :controller=>'pages', :action => 'update_page'
      resources :categories, :users, :sessions
      resources :medias do
        get :overview, :on => :collection
      end
    end
  end
end

app/models/blogr/category.rb
module Blogr
  class Category < ActiveRecord::Base
    set_table_name "blogr_categories"
    has_many :posts, :class_name => "Blogr::Post"
    validates_presence_of :title

  end
end

app/controllers/blogr/admin/categories_controller.rb
module Blogr
  class Admin::CategoriesController < Admin::BlogrAdminController
    unloadable

    before_filter :get_category, :only => [:edit, :update, :destroy, :publish]

    def index
      @categories = Category.page(params[:page])
    end

    def new
      @category = Category.new
    end

    def edit
    end

    def create
      @category = Category.new(params[:blogr_category])
      if @category.save
        Activity.create :who => current_user.name, :what => "New category created: #{@category.title}"
        redirect_to blogr_admin_categories_path, :notice => "Category was successfully created."
      else
        render :action => "new"
      end
    end

    def update
      if @category.update_attributes(params[:blogr_category])
        Activity.create :who => current_user.name, :what => "Category updated: #{@category.title}"
        redirect_to blogr_admin_categories_path, :notice => "Category was successfully updated."
      else
        render :action => "edit"
      end
    end

    def destroy
      @category.destroy
      Activity.create :who => current_user.name, :what => "Destroyed: #{@category.title}"
      redirect_to blogr_admin_categories_path, :notice => "Category was successfully deleted."
    end

    private

    def get_category
      @category = Category.find(params[:id])
    end
  end
end

app/views/blogr/admin/categories/_form.html.erb
<%= form_for @category, :url => blogr_admin_categories_path do |f|%>
    <%= render "blogr/shared/error_messages", :object => @category %>
    <table>
        <tr>
            <td><%= f.label :title%></td>
            <td><%= f.text_field :title%></td>
        </tr>
        <tr>
            <td><%= f.submit "create category", :class => "button button-green" %></td>
        </tr>
    </table>
<% end %>

app/views/blogr/admin/categories/edit.html.erb
<div class="posts-box main-content">
    <div class="posts-header">
        <ul class="action-buttons clearfix fr">
            <li><%#= link_to "new page", new_blogr_admin_page_path, :class => "button button-gray"%></li>
            <li><%= link_to "Back", blogr_admin_categories_path, :class => "button button-gray"%></li>
        </ul>
        <h2>Edit <%= @category.title%></h2>
    </div>
    <div class="posts-box-content">
        <div class="table">
            <%= form_for( @category, :url => blogr_admin_category_path(:id => @category.id), :html => { :method => "put"}) do |f|%>
                <%= render "blogr/shared/error_messages", :object => @category %>
                <table>
                    <tr>
                        <td><%= f.label :title%></td>
                        <td><%= f.text_field :title%></td>
                    </tr>
                    <tr>
                        <td><%= f.submit "create category", :class => "button button-green" %></td>
                    </tr>
                </table>
            <% end %>
        </div>
    </div>
</div>

app/views/blogr/admin/categories/index.html.erb
<div class="categories-box main-content">
    <div class="categories-header">
        <ul class="action-buttons clearfix fr">
            <li><%= link_to "New category", new_blogr_admin_category_path, :class => "button button-gray"%></li>
            <li><a href="#" class="button button-gray">Archive</a></li>
        </ul>
        <h2>Categories Index</h2>
    </div>
    <div class="categories-box-content">
        <div class="table">
            <table>
                <thead>
                    <tr>
                        <th><input class="check-all" type="checkbox"></th>
                        <th>Title</th>
                        <th>Posts</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <td colspan="6">
                            <div class="bulk-actions align-left">
                                <select name="dropdown">
                                    <option value="option1">Choose an action...</option>
                                    <option value="option2">Edit</option>
                                    <option value="option3">Delete</option>
                                </select>
                                <a class="button" href="#">Apply to selected</a>
                            </div>
                            <%= paginate @categories%>
                            <div class="clear"></div>
                        </td>
                    </tr>
                </tfoot>
                <tbody>
                    <% @categories.each do |category|%>
                        <tr class=<%= cycle("even", "odd")%>>
                            <td><input type="checkbox"></td>
                            <td><%= category.title%></td>
                            <td><%= category.posts.count%></td>
                            <td>
                                <%= link_to image_tag("edit.png"), edit_blogr_admin_category_path(category)%>
                                <%= link_to image_tag("delete.png"), blogr_admin_category_path(category), :method => :delete%>
                            </td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/blogr/admin/categories/new.html.erb
<div class="posts-box main-content">
    <div class="posts-header">
        <ul class="action-buttons clearfix fr">
            <li><%#= link_to "new page", new_blogr_admin_page_path, :class => "button button-gray"%></li>
            <li><%= link_to "Back", blogr_admin_categories_path, :class => "button button-gray"%></li>
        </ul>
        <h2>New Category</h2>
    </div>
    <div class="posts-box-content">
        <div class="table">
            <%= render "form"%>
        </div>
    </div>
</div>