config/routes.rb
Rails.application.routes.draw do
  scope "blog", :module => :blogr, :as => "blogr" do
    root :to => "posts#index"
    resources :posts, :only => [:index, :show] do
      resource :comments
    end
    resources :pages, :only => [:index, :show] do
      resources :inquiries
    end
    namespace :admin do
      root :to => "sessions#new"
      get "logout" => "sessions#destroy", :as => "logout"
      get "login" => "sessions#new", :as => "login"
      get "sign_up" => "users#new", :as => "sign_up"
      resources :posts do
        get :publish, :on => :member
        resource :comments
      end
      resources :sessions do
        get :dashboard, :on => :collection
      end
      resources :pages do
        get :hide, :on => :member
        get :unhide, :on => :member
      end
      match 'pages/update_positions/', :controller=>'pages', :action => 'update_positions'
      match 'pages/update_page/', :controller=>'pages', :action => 'update_page'
      resources :categories, :users, :sessions
      resources :medias do
        get :overview, :on => :collection
      end
    end
  end
end

app/views/layouts/blogr.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Rails engine blog</title>
    <meta name="description" content="Rails::Engine blog">
    <meta name="author" content="DanielZ">
    <%= stylesheet_link_tag("reset", "blogr", "css3buttons") %>
</head>
<body>
    <div class="container">
        <header>
            <h1 id="title"><%= link_to "Blog!", blogr_root_path %></h1>
        </header>
        <div id="menu">
            <%= render "blogr/shared/menu"%>
        </div>
        <div id="main">
            <%= yield %>
        </div>
    </div>
</body>
</html>

app/views/layouts/blogr_admin.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
    "http://www.w3.org/TR/html4/strict.dtd">
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Rails engine blog</title>
	<meta name="description" content="Rails::Engine blog">
	<meta name="author" content="DanielZ">
	<%= stylesheet_link_tag "admin", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.10/jquery-ui.min.js" %>
	<%= javascript_include_tag :all%>
	<%= javascript_include_tag  "blogr_admin","jquery", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.10/jquery-ui.min.js", "tiny_mce/jquery.tinymce.js", "jquery.tablednd_0_5.js", "jqrails.js" %>
	<%= csrf_meta_tag %>
    <script type="text/javascript">
    $().ready(function() {
        $('textarea.editor').tinymce({
            script_url : '/javascripts/tiny_mce/tiny_mce.js',
            theme : "advanced",
            skin : "cirkuit",
            plugins : "spellchecker,safari,pagebreak,style,layer,table,save,advimage,advlink,advlist,emotions,iespell,inlinepopups,insertdatetime,media,searchreplace,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template",

            theme_advanced_buttons1 : "formatselect,fontsizeselect,forecolor,|,bold,italic,strikethrough,|,bullist,numlist,|,justifyleft,justifycenter,justifyright,|,link,unlink,|,image",
            theme_advanced_buttons2 : "code,paste,pastetext,pasteword,removeformat,|,backcolor,|,underline,justifyfull,sup,|,outdent,indent,|,hr,anchor,charmap,|,media,|,search,replace,|,fullscreen,|,undo,redo",
            theme_advanced_buttons3 : "tablecontrols,|,visualaid",
            theme_advanced_layout_manager : "SimpleLayout",
            theme_advanced_toolbar_location : "top",
            theme_advanced_toolbar_align : "left",
            theme_advanced_statusbar_location : "bottom",
            theme_advanced_resizing : false,

            content_css : "/stylesheets/tinymce.css",
            template_external_list_url : "lists/template_list.js",
            external_link_list_url : "lists/link_list.js",
            external_image_list_url : "lists/image_list.js",
            media_external_list_url : "lists/media_list.js",
            // plugins : "autolink,lists,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,advlist",
            // theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect",
            // theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,undo,redo,|,link,unlink,anchor,image,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
            // theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,charmap,emotions,iespell,media,advhr,|,fullscreen",
        });
    });
    </script>
    <!-- /TinyMCE -->
</head>
<body>
    <div class="container">
        <div id="header">
            <% if current_user%>
            <h1 id="title"><%= link_to "Blog!", blogr_root_path %></h1>
                <div id="menu" class="menu-content">
                    <ul>
                        <li><%= link_to "Dash", "/blog/admin/sessions/dashboard"%></li>
                        <li><%= link_to "Pages", blogr_admin_pages_path%></li>
                        <li><%= link_to "Posts", blogr_admin_posts_path%></li>
                        <li><%= link_to "Categories", blogr_admin_categories_path%></li>
                        <li><%= link_to "Media", blogr_admin_medias_path%></li>
                        <li class="fr"><%= link_to "Logout", blogr_admin_logout_path %></li>
                    </ul>
                </div>
            <% end %>
        </div>
        <div id="main">
            <%= yield %>
        </div>
    </div>
</body>
</html>

app/views/layouts/images.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
    "http://www.w3.org/TR/html4/strict.dtd">
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Rails engine blog</title>
	<meta name="description" content="Rails::Engine blog">
	<meta name="author" content="DanielZ">
	<%= stylesheet_link_tag "admin", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.10/jquery-ui.min.js" %>
	<%= javascript_include_tag :all%>
	<%= javascript_include_tag  "blogr_admin","jquery", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.10/jquery-ui.min.js", "tiny_mce/jquery.tinymce.js", "jquery.tablednd_0_5.js", "jqrails.js" %>
	<%= csrf_meta_tag %>
</head>
<body>
    <div class="container">
        <div id="main">
            <%= yield %>
        </div>
    </div>
</body>
</html>